# Generated by Django 4.2.16 on 2026-05-03 13:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField(help_text='Что заявитель пишет организатору при подаче заявки.', validators=[django.core.validators.MinLengthValidator(1)], verbose_name='текст обращения')),
                ('status', models.CharField(choices=[('pending', 'на рассмотрении'), ('approved', 'одобрена'), ('rejected', 'отклонена'), ('cancelled', 'отозвана')], default='pending', max_length=16, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлена')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='заявитель')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='cats.cat', verbose_name='кот')),
            ],
            options={
                'verbose_name': 'заявка на ивент',
                'verbose_name_plural': 'заявки на ивенты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(default=False, verbose_name='закрыт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dialog', to='events.application', verbose_name='заявка')),
            ],
            options={
                'verbose_name': 'диалог',
                'verbose_name_plural': 'диалоги',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[django.core.validators.MinLengthValidator(1)], verbose_name='текст')),
                ('is_read', models.BooleanField(default=False, verbose_name='прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='отправлено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='events.dialog', verbose_name='диалог')),
            ],
            options={
                'verbose_name': 'сообщение',
                'verbose_name_plural': 'сообщения',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(4)], verbose_name='название')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('location', models.CharField(max_length=200, verbose_name='место проведения')),
                ('starts_at', models.DateTimeField(verbose_name='начало')),
                ('ends_at', models.DateTimeField(verbose_name='окончание')),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='количество мест')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлён')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_events', to=settings.AUTH_USER_MODEL, verbose_name='организатор')),
            ],
            options={
                'verbose_name': 'кото-ивент',
                'verbose_name_plural': 'кото-ивенты',
                'ordering': ('-starts_at',),
            },
        ),
        migrations.AddField(
            model_name='application',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='events.event', verbose_name='ивент'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(check=models.Q(('ends_at__gt', models.F('starts_at'))), name='event_ends_after_starts'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('event', 'cat'), name='unique_application_event_cat'),
        ),
    ]
