# Generated by Django 4.2.16 on 2026-05-03 12:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'достижение',
                'verbose_name_plural': 'достижения',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='кличка')),
                ('color', models.CharField(max_length=32, verbose_name='окрас')),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2026)], verbose_name='год рождения')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cats/', verbose_name='фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'кот',
                'verbose_name_plural': 'коты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='название')),
                ('slug', models.SlugField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='Slug может содержать только латиницу, цифры, _ и -.', regex='^[-a-zA-Z0-9_]+$')], verbose_name='slug')),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CatTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.cat')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.tag')),
            ],
        ),
        migrations.CreateModel(
            name='CatAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieved_at', models.DateField(auto_now_add=True, verbose_name='дата получения')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.achievement')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_achievements', to='cats.cat')),
            ],
            options={
                'verbose_name': 'достижение кота',
                'verbose_name_plural': 'достижения котов',
            },
        ),
        migrations.AddField(
            model_name='cat',
            name='achievements',
            field=models.ManyToManyField(blank=True, related_name='cats', through='cats.CatAchievement', to='cats.achievement'),
        ),
        migrations.AddField(
            model_name='cat',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cats', to=settings.AUTH_USER_MODEL, verbose_name='владелец'),
        ),
        migrations.AddField(
            model_name='cat',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='cats', through='cats.CatTag', to='cats.tag'),
        ),
        migrations.AddConstraint(
            model_name='cattag',
            constraint=models.UniqueConstraint(fields=('cat', 'tag'), name='unique_cat_tag'),
        ),
        migrations.AddConstraint(
            model_name='catachievement',
            constraint=models.UniqueConstraint(fields=('cat', 'achievement'), name='unique_cat_achievement'),
        ),
        migrations.AddConstraint(
            model_name='cat',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_cat_name_per_owner'),
        ),
    ]
